apiVersion: v1
kind: Service
metadata:
  name: bb-demo-service
spec:
  type: ClusterIP
  selector:
    app: bb-demo
  ports:
    - port: 5000
      targetPort: 5000
      #ClusterIP: 30023  # You can specify any port from 30000-32767
  type: ClusterIP